# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PodWhyDead < Formula
  desc "One command. Full death story of any Kubernetes pod."
  homepage "https://github.com/NotHarshhaa/pod-why-dead"
  version "0.1.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/NotHarshhaa/pod-why-dead/releases/download/v0.1.0/pod-why-dead_0.1.0_darwin_amd64.tar.gz"
      sha256 "598ccaefcb573368a9d42705417b2c1a1d339b1fc2adbdb075c69f310b05c582"

      def install
        bin.install "pod-why-dead"
      end
    end
    on_arm do
      url "https://github.com/NotHarshhaa/pod-why-dead/releases/download/v0.1.0/pod-why-dead_0.1.0_darwin_arm64.tar.gz"
      sha256 "1d7ca1e715f1d3c6807ec2a6ebdb75ff14d56daabed0d2cb88d25ab1e7090efa"

      def install
        bin.install "pod-why-dead"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/NotHarshhaa/pod-why-dead/releases/download/v0.1.0/pod-why-dead_0.1.0_linux_amd64.tar.gz"
        sha256 "84d9d4427e963f88609ccbfb7889abc0f26105038ff7bd7a9fd8ad6eda79d099"

        def install
          bin.install "pod-why-dead"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/NotHarshhaa/pod-why-dead/releases/download/v0.1.0/pod-why-dead_0.1.0_linux_arm64.tar.gz"
        sha256 "59970620b82aed05bd08a39c2639e7071123b4695ed401a5be588eda93ac691e"

        def install
          bin.install "pod-why-dead"
        end
      end
    end
  end

  test do
    system "#{bin}/pod-why-dead", "--help"
  end
end
