# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PodWhyDead < Formula
  desc "One command. Full death story of any Kubernetes pod."
  homepage "https://github.com/NotHarshhaa/pod-why-dead"
  version "0.2.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/NotHarshhaa/pod-why-dead/releases/download/v0.2.0/pod-why-dead_0.2.0_darwin_amd64.tar.gz"
      sha256 "94069a7debab61a213afdd9b25007de2671e87bdef1e897dc9a079d1eca342e9"

      def install
        bin.install "pod-why-dead"
      end
    end
    on_arm do
      url "https://github.com/NotHarshhaa/pod-why-dead/releases/download/v0.2.0/pod-why-dead_0.2.0_darwin_arm64.tar.gz"
      sha256 "cb255974a01aefe859b950c22b1e3ef253ac2fd9a37331bdfdb22a1ecacbfe5f"

      def install
        bin.install "pod-why-dead"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/NotHarshhaa/pod-why-dead/releases/download/v0.2.0/pod-why-dead_0.2.0_linux_amd64.tar.gz"
        sha256 "689abf6ce8a8bfcb28109dba41b22574c0c86fc5508466edf5d04c1259cc0814"

        def install
          bin.install "pod-why-dead"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/NotHarshhaa/pod-why-dead/releases/download/v0.2.0/pod-why-dead_0.2.0_linux_arm64.tar.gz"
        sha256 "cd70b64aa7e3e9116c062c8d51b9cfb692606723258b4abe256ce030d7a3f0d7"

        def install
          bin.install "pod-why-dead"
        end
      end
    end
  end

  test do
    system "#{bin}/pod-why-dead", "--help"
  end
end
